#!/usr/bin/env bash

if [[ -n "$REGISTRY_ID" ]]; then
    echo "Templating config.js with REGISTRY_ID=$REGISTRY_ID"
    sed -ie "s/REPLACE_ME/$REGISTRY_ID/g" static/js/config.js
fi

exec go run main.go
